version: '3.9'

services:
  jumpnetapp:
    build: ./JumpNetApp
    container_name: jumpnetapp
    ports:
      - "3001:3000"

  clouddiskapp:
    build: ./CloudDiskApp
    container_name: clouddiskapp
    ports:
      - "3002:3000"
